src/details/urls.py
from django.urls import path

from .views import HomeView, CheckinView, CheckoutView

app_name = 'details'

urlpatterns = [
    path('', HomeView, name='home'),
    path('checkin/', CheckinView, name='checkIn'),
    path('checkout/', CheckoutView, name='checkOut'),
]

src/entry_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('details.urls')),
    path('admin/', admin.site.urls),
]

src/details/models.py
from django.db import models
from django.utils import timezone

class Visitor(models.Model):
    visitorName = models.CharField(max_length=50)
    visitorEmail = models.EmailField(max_length=60)
    visitorContactNo = models.CharField(max_length=13)
    hostName = models.CharField(max_length=50)
    hostEmail = models.EmailField(max_length=60)
    hostContactNo = models.CharField(max_length=13)
    checkIn = models.DateTimeField(default=timezone.now)
    checkOut = models.DateTimeField(null=True)
    
    def __str__(self):
        return self.visitorName

src/details/forms.py
from django import forms

from .models import Visitor

class CheckinForm(forms.ModelForm):
    visitorName = forms.CharField(widget=forms.TextInput(attrs={
        "id": "visitorName",
        "class": "form-control",
        "placeholder": "Name",
        "autofocus": "True"
    }))
    visitorEmail = forms.EmailField(widget=forms.EmailInput(attrs={
        "id": "visitorEmail",
        "class": "form-control",
        "placeholder": "Email Address"
    }))
    visitorContactNo = forms.RegexField(regex=r'^\+?1?\d{9,15}$', error_messages={"invalid": "Enter a valid number"}, widget=forms.TextInput(attrs={
        "id": "visitorContactNo",
        "class": "form-control",
        "placeholder": "Phone No"
    }))
    hostName = forms.CharField(widget=forms.TextInput(attrs={
        "id": "hostName",
        "class": "form-control",
        "placeholder": "Name"
    }))
    hostEmail = forms.EmailField(widget=forms.EmailInput(attrs={
        "id": "hostEmail",
        "class": "form-control",
        "placeholder": "Email Address"
    }))
    hostContactNo = forms.RegexField(regex=r'^\+?1?\d{9,15}$', error_messages={"invalid": "Enter a valid number"}, widget=forms.TextInput(attrs={
        "id": "hostContactNo",
        "class": "form-control",
        "placeholder": "Phone No"
    }))
    class Meta:
        model = Visitor
        fields = [
            'visitorName',
            'visitorEmail',
            'visitorContactNo',
            'hostName',
            'hostEmail',
            'hostContactNo'
        ]
    
    def clean_visitorEmail(self):
        email = self.cleaned_data["visitorEmail"]
        try:
            visitor = Visitor.objects.get(visitorEmail=email, checkOut__isnull=True)
            print(visitor)
        except Visitor.DoesNotExist:
            visitor = None
        if visitor is None: 
            return email
        else:
            raise forms.ValidationError("Email already exists")
 
    

class CheckoutForm(forms.ModelForm):
    visitorEmail = forms.EmailField(widget=forms.EmailInput(attrs={
        "id": "visitorEmail",
        "class": "form-control",
        "placeholder": "Email Address",
        "autofocus": "True"
    }))
    class Meta:
        model = Visitor
        fields = [
            'visitorEmail'
        ]

    def clean_visitorEmail(self):
        email = self.cleaned_data["visitorEmail"]
        try:
            visitors = Visitor.objects.filter(visitorEmail=email)
        except Visitor.DoesNotExist:
            visitors = None

        if visitors: 
            for visitor in visitors:
                if not visitor.checkOut:
                    return email
            raise forms.ValidationError("User already checked-out")
        else:
            raise forms.ValidationError("Email address not found")
    

src/details/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from django.utils import timezone
import requests

from .models import Visitor
from .forms import CheckinForm, CheckoutForm

url = "https://www.fast2sms.com/dev/bulk"


def HomeView(request):
    return render(request, 'home.html', {})

def CheckinView(request):
    form = CheckinForm(request.POST or None)
    if form.is_valid():
        form.save()
        visitor = Visitor.objects.get(visitorEmail = form.cleaned_data.get('visitorEmail'), checkOut__isnull=True)
        check_in = visitor.checkIn.strftime('%B %d, %Y %l:%M:%S %p')
        my_msg = f'{visitor.visitorName} is here to meet you\nCheck-in Time: {check_in}\nContact Number: {visitor.visitorContactNo}\nEmail Address: {visitor.visitorEmail}'
        try:
            send_mail(
                    f'{visitor.visitorName} just checked in',
                    my_msg,
                    settings.EMAIL_HOST_USER,
                    [visitor.hostEmail],
                    fail_silently=True
                )
        except BadHeaderError:
            return redirect('details:home')

        host_num = visitor.hostContactNo
        auth_token = settings.AUTH_TOKEN

        payload = f"sender_id=FSTSMS&message={my_msg}&language=english&route=p&numbers={host_num}"
        headers = {
            'authorization': auth_token,
            'Content-Type': "application/x-www-form-urlencoded",
            'Cache-Control': "no-cache",
        }

        response = requests.request("POST", url, data=payload, headers=headers)
        messages.success(request, f"{visitor.visitorName} successfully checked in")
        return redirect('details:home')

    my_context = {
        'form': form
    }
    return render(request, 'checkin.html', my_context)

def CheckoutView(request):
    form = CheckoutForm(request.POST or None)
    if form.is_valid():
        visitor = Visitor.objects.get(visitorEmail=form.cleaned_data.get('visitorEmail'), checkOut__isnull=True)
        visitor.checkOut = timezone.now()
        visitor.save()
        check_out = visitor.checkOut.strftime('%B %d, %Y %l:%M:%S %p')
        check_in = visitor.checkIn.strftime('%B %d, %Y %l:%M:%S %p')
        my_msg = f"Name: {visitor.visitorName}\nPhone No.: {visitor.visitorContactNo}\nCheck-in Time: {check_in}\nCheck-out Time: {check_out}\nHost Name: {visitor.hostName}\nAddress visited: Innovacer Office"
        try:
            send_mail(
                    f'Your Visit to Innovacer',
                    my_msg,
                    settings.EMAIL_HOST_USER,
                    [visitor.visitorEmail],
                    fail_silently=True
                )
        except BadHeaderError:
            return redirect('details:home')
        
        messages.success(request, f"{visitor.visitorName} successfully checked out")
        return redirect('details:home')

    my_context = {
        'form': form
    }
    return render(request, 'checkout.html', my_context)

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        <title>Entry Management</title>
    </head>
    <body>
        
        <div class="masthead">
            
            <div class="container h-100">
                <div style="text-align: center">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}}" id="msg" role="alert">
                                {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="row h-100 align-items-center">
                    
                    {% block content %}
                        replace me
                    {% endblock content %}
                
                </div>
            </div>
        </div>
    
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <script>
            setTimeout(function(){
                if ($('#msg').length > 0) {
                    $('#msg').remove();
                }
            }, 2000)
        </script>
        
    </body>
</html>

src/templates/checkin.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}}" id="msg" role="alert" style="position: absolute;">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Check In</h5>
                    <form method='POST' class="form-signin" id="checkin-form"> {% csrf_token %}
                        <label>Visitor details</label>
                        <div class="form-label-group">
                            {{ form.visitorName }}
                            {{form.visitorName.errors}}
                            <label for="visitorName">Name</label>
                        </div>

                        <div class="form-label-group">
                            {{ form.visitorEmail }}
                            {{ form.visitorEmail.errors }}
                            <label for="visitorEmail">Email Address</label>
                        </div>

                        <div class="form-label-group">
                            {{ form.visitorContactNo }}
                            {{ form.visitorContactNo.errors }}
                            <label for="visitorContactNo">Phone No</label>
                        </div>
                        <hr class="my-4">
                        <label>Host details</label>
                        <div class="form-label-group">
                            {{ form.hostName }}
                            {{ form.hostName.errors }}
                            <label for="hostName">Name</label>
                        </div>

                        <div class="form-label-group">
                            {{ form.hostEmail }}
                            {{ form.hostEmail.errors }}
                            <label for="hostEmail">Email address</label>
                        </div>

                        <div class="form-label-group">
                            {{ form.hostContactNo }}
                            {{ form.hostContactNo.errors }}
                            <label for="hostContactNo">Phone No</label>
                        </div>

                        <a class="btn btn-lg btn-primary text-uppercase" style="margin-right:3%;" href="{% url 'details:home' %}">Back</a>
                        <button class="btn btn-lg btn-primary text-uppercase" style="margin-left:3%;" type="submit">Check In</button>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

src/templates/checkout.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Check Out</h5>
                    <form class="form-signin" method='POST'> {% csrf_token %} 
                        <div class="form-label-group">
                            {{ form.visitorEmail }}
                            {{ form.visitorEmail.errors }}
                            <label for="visitorEmail">Email address</label>
                        </div>  

                        <a class="btn btn-lg btn-primary text-uppercase" style="margin-right:3%;" href="{% url 'details:home' %}">Back</a>
                        <button class="btn btn-lg btn-primary text-uppercase" style="margin-left:3%;" type="submit">Check Out</button>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

src/templates/home.html
{% extends 'base.html' %}

{% block content %}

    <div class="col-12 text-center" style="margin-bottom: 40px;">
        <h1 class="display-4" style="padding-bottom:10px;color:floralwhite;">Entry Management</h1>  
        <a class="btn btn-outline-light btn-lg mr-1" href="{% url 'details:checkIn' %}" role="button">Check In</a>
        <a class="btn btn-outline-light btn-lg ml-1" href="{% url 'details:checkOut' %}" role="button">Check Out</a>
    </div
{% endblock content %}